In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression, load_diabetes
from sklearn.model_selection import train_test_split

## Diabetes Data

In [8]:
data = load_diabetes()

## Custom Regression Data

In [9]:
X, y = make_regression(
    n_samples=1000,
    n_features=20,
    n_informative=15,
    n_targets=1,
    noise=0.5
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1999)

In [10]:
df_train = pd.DataFrame(
    np.column_stack((X_train, y_train)),
    columns=[f'feature_{i}' for i in range(X_train.shape[1])] + ['target']
)
df_train.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,target
0,0.672968,1.925879,0.427093,-0.850174,0.507976,-1.454321,-0.849492,-0.943203,-0.192567,0.293146,...,-0.421797,0.034377,0.361717,1.490719,-0.382858,-1.035218,-0.674660,-0.052313,0.158217,3.111873
1,0.762914,-0.284632,-0.956225,-1.661710,-1.427453,-0.029390,-0.671369,1.151833,-0.330386,-1.388519,...,-1.477292,0.421916,-0.725699,-2.149097,1.091661,0.528656,-0.254750,0.324347,-1.317739,-472.504382
2,1.054416,-0.687419,-0.297820,1.368112,0.011855,-0.320341,1.238080,0.062881,-0.260086,-0.950711,...,-0.299232,-2.049302,-0.010633,-0.899608,0.482894,1.493051,1.659727,1.581748,1.203460,232.730987
3,0.454817,0.792578,0.365253,0.370623,-0.272989,1.180243,0.382384,0.770692,-0.426720,0.337903,...,0.341138,-0.885979,0.799870,-0.303508,1.999256,0.533791,-1.159029,0.688447,0.332085,198.392684
4,0.145493,-1.930951,-0.512839,-1.153429,-0.571989,0.548261,0.846353,-0.505430,-0.236906,0.259875,...,-0.187847,-0.827669,-0.393216,1.135052,0.335324,0.641668,0.771409,-0.471550,-0.956011,102.008569

In [11]:
df_test = pd.DataFrame(
    np.column_stack((X_test, y_test)),
    columns=[f'feature_{i}' for i in range(X_test.shape[1])] + ['target']
)
df_test.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,target
0,-1.250659,0.435500,-1.020463,0.408604,-0.507406,0.012479,1.040426,-0.295082,-1.527450,0.620785,...,-1.809474,-0.952542,-1.246310,0.665827,-1.304000,0.429845,-0.744455,-0.774084,0.471174,-53.825573
1,0.643785,1.228254,0.513795,-0.538547,-2.182566,0.787653,-0.718478,-2.243023,-0.039325,2.049866,...,-0.408339,-0.925896,-0.872217,0.597535,-0.968517,-0.976932,0.723719,0.017624,0.179720,-48.940087
2,-0.294731,-0.904933,0.478760,-1.083573,1.817771,1.335916,-0.664230,3.320381,-0.594839,0.091491,...,0.354634,-0.297474,-2.583014,-0.095101,0.005942,-0.278888,-1.433926,0.999226,1.480411,33.060448
3,-0.758932,1.064898,0.436227,1.387161,-0.216915,0.852867,0.571521,-0.936255,-0.693844,1.667367,...,1.559276,-0.247755,-1.349718,-1.336725,0.398074,-0.072257,0.697907,-0.034994,0.138189,-6.885086
4,0.200322,-2.987255,-0.898783,-0.038008,-0.117509,-0.815801,2.507305,-0.090630,3.035861,-0.066556,...,-0.411527,-0.598451,-1.257255,-1.217333,0.334243,-0.144406,-1.368476,-1.637705,0.485639,-173.523530

In [12]:
df_train.to_csv("regression_data_train.csv", index=False)
df_test.to_csv("regression_data_test.csv", index=False)